spring:
  application:
    name: educational-platform

  #  database
  datasource:
    url: jdbc:mysql://100.64.0.4:3306/educationalplatform
    username: educationalplatform
    password: educationalplatform
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
