spring:
  application:
    name: educational-platform

  #  database
  datasource:
    url: jdbc:mysql://100.64.0.4:3306/educationalplatform
    username: educationalplatform
    password: educationalplatform
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: id_deleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值